spring:
  application:
    name: visits-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

---
spring:
  config:
    activate:
      on-profile: chaos-monkey
    import: configserver:http://config-server:8888

chaos:
  monkey:
    enabled: true
    watcher:
      service: true
      controller: true
      restController: true
      component: true
    assaults:
      latencyActive: false
      exceptionsActive: true
      level: 1

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"