receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

  memory_limiter:
    limit_mib: 100
    check_interval: 5s

exporters:
  awscloudwatchlogs:
    log_group_name: "petclinic"
    log_stream_name: "dice"
    region: "ap-northeast-1"
    log_retention: 1

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter,batch]
      exporters: [awscloudwatchlogs]
