receivers:
  otlp:
    protocols:
      grpc:
      http:

  zipkin:

processors:
  batch:

  memory_limiter:
    limit_mib: 100
    check_interval: 5s

exporters:
  awscloudwatchlogs:
    log_group_name: "petsearch"
    log_stream_name: "app"
    region: "ap-northeast-1"
    log_retention: 7

  awsxray:
    region: ap-northeast-1

  otlphttp:
    endpoint: http://cw-agent:4316

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter,batch]
      exporters: [awscloudwatchlogs]
    
    traces:
      receivers: [zipkin]
      processors: [memory_limiter,batch]
      exporters: [otlphttp]
