services:
  app:
    build: ./dice
    ports:
      - 8080:8080
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_PROPAGATORS=xray,tracecontext,baggage,b3
      - OTEL_RESOURCE_ATTRIBUTES=service.name=dice-server,aws.log.group.names=dice-server
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://cw-agent:4316/v1/traces
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://adot:4318/v1/logs
      - OTEL_AWS_APPLICATION_SIGNALS_EXPORTER_ENDPOINT=http://cw-agent:4316/v1/metrics
      - OTEL_AWS_APPLICATION_SIGNALS_ENABLED=true
      - OTEL_TRACES_SAMPLER=always_on
      - JAVA_TOOL_OPTIONS="-javaagent:/app/aws-opentelemetry-agent.jar"

  cw-agent:
    image: public.ecr.aws/cloudwatch-agent/cloudwatch-agent:1.300044.0b793
    container_name: cw-agent
    volumes:
      - ./cwagent.json:/etc/cwagentconfig
    ports:
      - 4316:4316

  adot:
    image: public.ecr.aws/aws-observability/aws-otel-collector:v0.40.0
    container_name: adot
    command:
      - --config=/etc/otel-config.yaml
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    ports:
      - 4318:4318
