receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
        tls:
          insecure: false

processors:
  batch:

  memory_limiter:
    limit_mib: 100
    check_interval: 5s

exporters:
  awscloudwatchlogs:
    log_group_name: "dice-server"
    log_stream_name: "dice"
    region: "ap-northeast-1"
    log_retention: 7

  otlphttp:
    endpoint: "http://cw-agent:4316/v1/traces"

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter,batch]
      exporters: [awscloudwatchlogs]

    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp]

